POST http://localhost:9900/databinder
Content-Type: application/x-www-form-urlencoded

test=99&date=2020-6-24

###
POST http://localhost:9900/databinderData
Content-Type: application/json

{
  "test": "99",
  "date": "2020-06-24"
}
###
GET http://localhost:9900/databinder?test=123
Accept: application/json

###

POST http://localhost:9900/databinderMap
Content-Type: application/json

{
  "map1":"123",
  "map2":"456"
}

###

POST http://localhost:9900/databinderString
Content-Type: text/plain

{
  "map1\":\"123\",  \"map2\":\"456"
}

###

POST http://localhost:9900/databinderString
Content-Type: multipart/form-data
